#!/bin/bash
case "$1" in
	"start")
		rc-service $2 start
		;;
	"stop")
		rc-service $2 stop
		;;
	"restart")
		rc-service $2 restart
		;;
	"status")
		rc-service $2 status
		;;
	"list-units")
		rc-status
		;;
	"list-unit-files")
		rc-update -v show
		;;
	"enable")
		rc-update add $2 default
		;;
	"disable")
		rc-update del $2 default
		;;
esac
exit